/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.srm.services.standalone.settings;

import com.srm.services.config.ServiceConstant;
import com.srm.services.modal.HeaderSettings;
import com.srm.services.services.HeaderService;
import com.srm.services.standalone.utils.StandaloneUtils;
import javax.annotation.PostConstruct;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author umprasad
 */
@Component
public class HeaderSetting extends javax.swing.JDialog {

    @PostConstruct
    public void init(){
         initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFieldComapnyName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFieldAddress = new javax.swing.JTextField();
        txtFieldAdressSub = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFieldContactNo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFieldRegstrationNo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jRadioYes = new javax.swing.JRadioButton();
        jRadioNo = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        findActionBtn = new javax.swing.JButton();
        saveActionBtn = new javax.swing.JButton();
        clearActionBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Header Settings");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51)));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Company/Shop Name");

        txtFieldComapnyName.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Address");

        txtFieldAddress.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        txtFieldAdressSub.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Contact No.");

        txtFieldContactNo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Regstration No.");

        txtFieldRegstrationNo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Print Address");

        buttonGroup1.add(jRadioYes);
        jRadioYes.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jRadioYes.setSelected(true);
        jRadioYes.setText("Yes");

        buttonGroup1.add(jRadioNo);
        jRadioNo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jRadioNo.setText("No");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtFieldAdressSub, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioYes)
                                .addGap(45, 45, 45)
                                .addComponent(jRadioNo))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtFieldComapnyName)
                                .addComponent(txtFieldAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
                                .addComponent(txtFieldContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFieldRegstrationNo)))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFieldComapnyName, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(37, 37, 37)
                .addComponent(txtFieldAdressSub, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFieldContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFieldRegstrationNo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRadioYes)
                    .addComponent(jRadioNo))
                .addGap(32, 32, 32))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        findActionBtn.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        findActionBtn.setText("Find");
        findActionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findActionBtnActionPerformed(evt);
            }
        });

        saveActionBtn.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        saveActionBtn.setText("Save");
        saveActionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionBtnActionPerformed(evt);
            }
        });

        clearActionBtn.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        clearActionBtn.setText("Clear");
        clearActionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(findActionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveActionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clearActionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findActionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveActionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearActionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionBtnActionPerformed
      try{
            if(headerSettings==null){headerSettings=new HeaderSettings();}
                headerSettings.setCompanyName(txtFieldComapnyName.getText());
                headerSettings.setAddress(txtFieldAddress.getText());
                headerSettings.setAddressSub(txtFieldAdressSub.getText());
                headerSettings.setContactNo(txtFieldContactNo.getText());
                headerSettings.setRegistrationNo(txtFieldRegstrationNo.getText());
                String addressUse=jRadioYes.isSelected()?ServiceConstant.DEFAULT_USE_YES:ServiceConstant.DEFAULT_USE_NO;
                headerSettings.setDefaultUse(addressUse);
            if(headerSettings.getId()==null){
                 headerSettings=headerService.save(headerSettings);
                 if(headerSettings.getId()!=null){
                     dialogBox(ServiceConstant.ACTION_SAVE);
                 }
            }else{
                headerService.save(headerSettings);
                dialogBox(ServiceConstant.ACTION_UPDATE);
            }
      }catch(Exception ex){
            StandaloneUtils.dialogBox(ServiceConstant.TECHNICAL_ERROR_MSG,this);
      }
    }//GEN-LAST:event_saveActionBtnActionPerformed

    private void clearActionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionBtnActionPerformed
        clearFields(jPanel1);
        jRadioYes.setSelected(Boolean.TRUE);
        headerSettings=null;
    }//GEN-LAST:event_clearActionBtnActionPerformed

    private void findActionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findActionBtnActionPerformed
       headerSettings=headerService.findByDefaultValue(ServiceConstant.DEFAULT_USE_YES);
       if(headerSettings!=null){
            txtFieldComapnyName.setText(headerSettings.getCompanyName());
            txtFieldAddress.setText(headerSettings.getAddress());
            txtFieldAdressSub.setText(headerSettings.getAddressSub());
            txtFieldContactNo.setText(headerSettings.getContactNo());
            txtFieldRegstrationNo.setText(headerSettings.getRegistrationNo());
            if(ServiceConstant.DEFAULT_USE_YES.equals(headerSettings.getDefaultUse())){
                jRadioYes.setSelected(Boolean.TRUE);
            }else{
                jRadioNo.setSelected(Boolean.FALSE);
            }
       }
    }//GEN-LAST:event_findActionBtnActionPerformed
    private void clearFields(java.awt.Component component){
        if(component instanceof JPanel){
            for(java.awt.Component comp:((JPanel)component).getComponents()){
                 if(comp instanceof  JTextField){
                     ((JTextField)comp).setText("");
                 }else if(comp instanceof JComboBox){
                     ((JComboBox)comp).setSelectedIndex(0);
                 }
            }
        }
    }
    private void dialogBox(Integer action){
       if(ServiceConstant.ACTION_SAVE.equals(action)){
         JOptionPane.showMessageDialog(this, ServiceConstant.SUCCESS_MSG, ServiceConstant.RESULT_SUCCESS,
                        JOptionPane.INFORMATION_MESSAGE);
       }else if(ServiceConstant.ACTION_UPDATE.equals(action)){
        JOptionPane.showMessageDialog(this, ServiceConstant.UPDATE_MSG, ServiceConstant.RESULT_SUCCESS,
                        JOptionPane.INFORMATION_MESSAGE);   
       }else if(ServiceConstant.ACTION_DELETE.equals(action)){
        JOptionPane.showMessageDialog(this, ServiceConstant.DETLE_MSG, ServiceConstant.RESULT_SUCCESS,
                        JOptionPane.INFORMATION_MESSAGE);   
       }
    }
    
    private HeaderSettings headerSettings;
    
    @Autowired
    private HeaderService headerService;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clearActionBtn;
    private javax.swing.JButton findActionBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioNo;
    private javax.swing.JRadioButton jRadioYes;
    private javax.swing.JButton saveActionBtn;
    private javax.swing.JTextField txtFieldAddress;
    private javax.swing.JTextField txtFieldAdressSub;
    private javax.swing.JTextField txtFieldComapnyName;
    private javax.swing.JTextField txtFieldContactNo;
    private javax.swing.JTextField txtFieldRegstrationNo;
    // End of variables declaration//GEN-END:variables
}
